const employee1 = ["1","Thompson","Anthony","32","Male","Head of Finance Department","17/07/2014"]
const employee2 = ["2","Johnson","Mary","23","Female","Software Engineer","05/03/2019"]
const employee3 = ["3","Chisom","Onyeka","28","Female","Human Resource Manager","21/06/2016"]
const employee4 = ["4","Jide","Olabisi","29","Male","Assistant Head(Software Department)","06/09/2015"]
const employee5 = ["5","Williams","Ajayi","30","Male","Head of Software Department","06/09/2016"]
const employee6 = ["6","Nancy","Chukwuemeka","27","Female","Secretary","23/08/2016"]
const employee7 = ["7","Nicholas","Uchema","26","Male","Software Engineer","22/02/2022"]
const employee8 = ["8","Ahmed","Olayinka","24","Male","Graphic Designer","15/08/2020"]
const employee9 = ["9","Halima","Mohammed","26","Female","Senior Finance Manager","30/05/2018"]
const employee0 = ["10","Richard","Adeyemi","40","Male","C.E.O","17/07/2014"]





document.getElementById("a1").innerHTML = employee1[0]
document.getElementById("a2").innerHTML = employee1[1]
document.getElementById("a3").innerHTML = employee1[2]
document.getElementById("a4").innerHTML = employee1[3]
document.getElementById("a5").innerHTML = employee1[4]
document.getElementById("a6").innerHTML = employee1[5]
document.getElementById("a7").innerHTML = employee1[6]

document.getElementById("b1").innerHTML = employee2[0]
document.getElementById("b2").innerHTML = employee2[1]
document.getElementById("b3").innerHTML = employee2[2]
document.getElementById("b4").innerHTML = employee2[3]
document.getElementById("b5").innerHTML = employee2[4]
document.getElementById("b6").innerHTML = employee2[5]
document.getElementById("b7").innerHTML = employee2[6]

document.getElementById("c1").innerHTML = employee3[0]
document.getElementById("c2").innerHTML = employee3[1]
document.getElementById("c3").innerHTML = employee3[2]
document.getElementById("c4").innerHTML = employee3[3]
document.getElementById("c5").innerHTML = employee3[4]
document.getElementById("c6").innerHTML = employee3[5]
document.getElementById("c7").innerHTML = employee3[6]

document.getElementById("d1").innerHTML = employee4[0]
document.getElementById("d2").innerHTML = employee4[1]
document.getElementById("d3").innerHTML = employee4[2]
document.getElementById("d4").innerHTML = employee4[3]
document.getElementById("d5").innerHTML = employee4[4]
document.getElementById("d6").innerHTML = employee4[5]
document.getElementById("d7").innerHTML = employee4[6]

document.getElementById("e1").innerHTML = employee5[0]
document.getElementById("e2").innerHTML = employee5[1]
document.getElementById("e3").innerHTML = employee5[2]
document.getElementById("e4").innerHTML = employee5[3]
document.getElementById("e5").innerHTML = employee5[4]
document.getElementById("e6").innerHTML = employee5[5]
document.getElementById("e7").innerHTML = employee5[6]

document.getElementById("f1").innerHTML = employee6[0]
document.getElementById("f2").innerHTML = employee6[1]
document.getElementById("f3").innerHTML = employee6[2]
document.getElementById("f4").innerHTML = employee6[3]
document.getElementById("f5").innerHTML = employee6[4]
document.getElementById("f6").innerHTML = employee6[5]
document.getElementById("f7").innerHTML = employee6[6]

document.getElementById("g1").innerHTML = employee7[0]
document.getElementById("g2").innerHTML = employee7[1]
document.getElementById("g3").innerHTML = employee7[2]
document.getElementById("g4").innerHTML = employee7[3]
document.getElementById("g5").innerHTML = employee7[4]
document.getElementById("g6").innerHTML = employee7[5]
document.getElementById("g7").innerHTML = employee7[6]

document.getElementById("h1").innerHTML = employee8[0]
document.getElementById("h2").innerHTML = employee8[1]
document.getElementById("h3").innerHTML = employee8[2]
document.getElementById("h4").innerHTML = employee8[3]
document.getElementById("h5").innerHTML = employee8[4]
document.getElementById("h6").innerHTML = employee8[5]
document.getElementById("h7").innerHTML = employee8[6]

document.getElementById("i1").innerHTML = employee9[0]
document.getElementById("i2").innerHTML = employee9[1]
document.getElementById("i3").innerHTML = employee9[2]
document.getElementById("i4").innerHTML = employee9[3]
document.getElementById("i5").innerHTML = employee9[4]
document.getElementById("i6").innerHTML = employee9[5]
document.getElementById("i7").innerHTML = employee9[6]

document.getElementById("j1").innerHTML = employee0[0]
document.getElementById("j2").innerHTML = employee0[1]
document.getElementById("j3").innerHTML = employee0[2]
document.getElementById("j4").innerHTML = employee0[3]
document.getElementById("j5").innerHTML = employee0[4]
document.getElementById("j6").innerHTML = employee0[5]
document.getElementById("j7").innerHTML = employee0[6]


